export { ProductImageGallery } from "./ProductImageGallery";
export { ProductInfo } from "./ProductInfo";
export { ProductSpecifications } from "./ProductSpecifications";
export { ProductDetailsTabs } from "./ProductDetailsTabs";
export { FAQSection } from "./FAQSection";
export { RecommendedAccessories } from "./RecommendedAccessories";
export { PreviouslyViewed } from "./PreviouslyViewed";
export { ShopByReels } from "./ShopByReels";
export { ProductDetailClient } from "./ProductDetailClient";
